require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/work_types", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WorkType. As you add validations to WorkType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WorkType.create! valid_attributes
      get work_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      work_type = WorkType.create! valid_attributes
      get work_type_url(work_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_work_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      work_type = WorkType.create! valid_attributes
      get edit_work_type_url(work_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WorkType" do
        expect {
          post work_types_url, params: { work_type: valid_attributes }
        }.to change(WorkType, :count).by(1)
      end

      it "redirects to the created work_type" do
        post work_types_url, params: { work_type: valid_attributes }
        expect(response).to redirect_to(work_type_url(WorkType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WorkType" do
        expect {
          post work_types_url, params: { work_type: invalid_attributes }
        }.to change(WorkType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post work_types_url, params: { work_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested work_type" do
        work_type = WorkType.create! valid_attributes
        patch work_type_url(work_type), params: { work_type: new_attributes }
        work_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the work_type" do
        work_type = WorkType.create! valid_attributes
        patch work_type_url(work_type), params: { work_type: new_attributes }
        work_type.reload
        expect(response).to redirect_to(work_type_url(work_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        work_type = WorkType.create! valid_attributes
        patch work_type_url(work_type), params: { work_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested work_type" do
      work_type = WorkType.create! valid_attributes
      expect {
        delete work_type_url(work_type)
      }.to change(WorkType, :count).by(-1)
    end

    it "redirects to the work_types list" do
      work_type = WorkType.create! valid_attributes
      delete work_type_url(work_type)
      expect(response).to redirect_to(work_types_url)
    end
  end
end
